model: 'fpn_cov1d' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 2000
n_epoch: 400
n_kfolds: 5
noise_level: 0.1
drop_rate: 0.05


#bnn parameter
inference: 'nuts' # 'nuts' 'svi' 'hmc'
n_samples: 100
warmup: 50
step_size: 0.001
num_steps: 40
# svi parameter
lr_svi: 0.01
n_epoch_svi: 200
# fnn setting
max_n_rules: 50

n_rules: 50
n_rules_fs: 2
lr: 0.001

dataset_folder: 'gas_drift' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['gas_drift']

#logger
log_to_file: 'true' # 'false' 'true'