model: 'fpn_mlpB' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 30
n_epoch: 300
n_kfolds: 5
noise_level: 0.5
drop_rate: 0.0


#bnn parameter
inference: 'nuts' # 'nuts' 'svi' 'hmc'
n_samples: 100
warmup: 50
step_size: 0.001
num_steps: 40
# svi parameter
lr_svi: 0.01
n_epoch_svi: 200


#gni sigma
gni_sigma: 0.01

n_rules: 5
n_rules_fs: 2
lr: 0.0005

dataset_folder: 'flowmeter' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['MeterD']

#logger
log_to_file: 'true' # 'false' 'true'