model: 'fpn_cov1d' #

device: 'cuda:0' # 'cpu' 'cuda:0'
n_batch: 3000
n_epoch: 500
n_kfolds: 5
noise_level: 0.0
drop_rate: 0.05

#gni sigma
gni_sigma: 0.01
# fnn setting
max_n_rules: 50

#bnn parameter
inference: 'nuts' # 'nuts' 'svi' 'hmc'
n_samples: 100
warmup: 50
step_size: 0.001
num_steps: 40

# svi parameter
lr_svi: 0.01
n_epoch_svi: 200
#dgp parameter
lr_dgp: 0.0005
n_epoch_dgp: 100
n_rules: 15
n_rules_fs: 2
lr: 0.001

dataset_folder: 'wine' # each kind of dataset has a same prefix name, dataset is the prefix
dataset_list:
  ['white']

#logger
log_to_file: 'true' # 'false' 'true'